# Generated by Django 5.1.7 on 2025-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
